import { readFile } from "node:fs/promises";
import path from "node:path";

const root = process.cwd();

async function read(relativePath) {
  return readFile(path.join(root, relativePath), "utf8");
}

function assert(condition, message) {
  if (!condition) {
    console.error(`smoke check: ${message}`);
    process.exitCode = 1;
  }
}

const [index, data, progress, kpi, app, embed, learning, manifest] = await Promise.all([
  read("index.html"),
  read("js/data.js"),
  read("js/progress.js"),
  read("js/math-learning-kpi.js"),
  read("js/app.js"),
  read("js/math-curriculum-embed.js"),
  read("js/math-learning-content.js"),
  read("curriculum/math/learning-slice-ids.json"),
]);

[
  "onboarding-root",
  "main-app",
  "home-big-pct",
  "home-subj-list",
  "stack-subject-detail",
  "stack-topic",
  "stack-activity",
  "profile-grade-value",
].forEach((id) => assert(index.includes(`id="${id}"`), `missing #${id} in index.html`));

[
  "window.SHANKS_DATA",
  "curriculumMathVersion",
  "learningMvp",
  "onboardingGoals",
].forEach((needle) => assert(data.includes(needle), `missing ${needle} in js/data.js`));

[
  "loadMathCurriculumIntoD",
  "completeTopicStep",
  "getLearningContent",
  "getMathKpiIdSet",
  "filterMathKpiTopicsIfConfigured",
  "exposeQaPilotTools",
  "renderActivity",
  "renderTopic",
  "renderProfile",
].forEach((needle) => assert(app.includes(needle), `missing ${needle} in js/app.js`));

assert(kpi.includes("window.SHANKS_MATH_KPI"), "math-learning-kpi.js must export SHANKS_MATH_KPI");

["window.SHANKS_PROGRESS", "topicKey", "topicPct", "isTestUnlocked", "getPracticePassRule"].forEach((needle) =>
  assert(progress.includes(needle), `missing ${needle} in js/progress.js`)
);

assert(
  learning.includes("window.SHANKS_MATH_LEARNING") && learning.includes("g8-u01"),
  "math-learning-content.js must define slice topics"
);

assert(index.includes("math-learning-kpi.js"), "index.html must load math-learning-kpi.js");

const manifestIds = JSON.parse(manifest).byGrade["8"];
assert(Array.isArray(manifestIds) && manifestIds.length > 0, "learning-slice-ids.json byGrade.8 must be array");
manifestIds.forEach((id) =>
  assert(learning.includes(`"${id}"`), `math-learning-content.js must include topic ${id}`)
);

assert(
  embed.startsWith("// Generated from curriculum/math/*.json"),
  "math embed must be generated by scripts/generate-math-embed.mjs"
);

const verMatch = data.match(/curriculumMathVersion:\s*"([^"]+)"/);
assert(verMatch, "js/data.js must set curriculumMathVersion");
const curriculumVer = verMatch[1];

/** Локальные css/js в index.html — все ?v= должны совпадать с curriculumMathVersion (синхронный cache-bust). */
function collectIndexCacheVersions(html) {
  const out = [];
  const linkRe = /href="([^"]+\.css)\?v=([^"]+)"/g;
  let m;
  while ((m = linkRe.exec(html)) !== null) {
    if (m[1].includes("fonts.googleapis.com")) continue;
    out.push({ asset: m[1], v: m[2] });
  }
  const scriptRe = /src="(js\/[^"?]+\.js)\?v=([^"]+)"/g;
  while ((m = scriptRe.exec(html)) !== null) {
    out.push({ asset: m[1], v: m[2] });
  }
  return out;
}

const indexVersions = collectIndexCacheVersions(index);
assert(indexVersions.length > 0, "index.html must have at least one local ?v= on css or js");
indexVersions.forEach(({ asset, v }) => {
  assert(
    v === curriculumVer,
    `cache-bust mismatch: ${asset} has ?v=${v}, js/data.js curriculumMathVersion is "${curriculumVer}"`
  );
});

if (!process.exitCode) {
  console.log("smoke check: critical files ok");
}
